### ISSUE TITLE
Moving to official WiringPi-Python

### ISSUE THREAD

**Issue by JokerQyou** [guyc/py-gaugette#18]
It seems like https://github.com/Gadgetoid/WiringPi2-Python is now marked as deprecated, and the official WiringPi-Python binding is now alive at https://github.com/WiringPi/WiringPi-Python. The problem is, the official package is now using `wiringpi` as the package name (for importing) rather than the old `wiringpi2`. I suggest that we migrate to the official package as soon as possible.

I'll try to help, but I only have a Raspberry Pi B+, thus cannot test the code on other hardwares.

**Comment by guyc** [comment]
Thanks for the PR.
